// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxuhU38FDxCQjGZ2rIoR4Qk23DmXZeT3E',
    appId: '1:224870115987:android:3b43ee759491c222ee3b66',
    messagingSenderId: '224870115987',
    projectId: 'pushnotidemo-e9c59',
    storageBucket: 'pushnotidemo-e9c59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfpSdFTgkse5K3gBvwOo0LS8fjIwhRSzs',
    appId: '1:224870115987:ios:8e6dfdb34ef422f2ee3b66',
    messagingSenderId: '224870115987',
    projectId: 'pushnotidemo-e9c59',
    storageBucket: 'pushnotidemo-e9c59.firebasestorage.app',
    androidClientId: '224870115987-im35vr8ud0i4fi1gq73e3vpp601vnht9.apps.googleusercontent.com',
    iosBundleId: 'com.sososi.classConnectAppFltr',
  );
}
